### ISSUE TITLE
some questions about running the internalblue on the ubuntu.

### ISSUE THREAD

**Issue by Wi1L-Y** [purseclab/lightblue#1]
when I try to run internalblue on my own laptop(ubuntu 18.04). It shows error("Not running on a Broadcom or Cypress chip!") . After analyzing the source code, I find there is a "vendor check", should I delete it? Or how can I run it on Ubuntu?

**Comment by wuruoyu** [comment]
Thank you for your question!

The short answer: you should not delete it, and possibly you cannot run the whole pipeline on your machine (not Ubuntu). And followings are explanation:

```internalblue``` only supports Broadcom/Cypress Bluetooth chip, since it does not have the knowledge to interact with the firmware from other vendors. 

I think the most likely situation is that your machine's Bluetooth chip is from other vendors. You can check your Bluetooth chip vendor by [sending HCI command](https://github.com/seemoo-lab/internalblue/blob/5460f57275833ec91a12efc5771b8a6ae843d3a9/internalblue/core.py#L707)  and looking up the vendor ID [here](https://www.bluetooth.com/specifications/assigned-numbers/company-identifiers/). 

The controller (firmware) debloating part of Lightblue relies on ```internalblue```. However, you should be able run host debloating without ```internalblue```.

**Comment by Wi1L-Y** [comment]
Thank you for your answer.

**Comment by Wi1L-Y** [comment]
Thank you four your answer!

**Comment by Wi1L-Y** [comment]
Thank you for your answer !

I thought about the question of chip version a few days ago and your explanation is very well.  I will try to get another machine for testing. Anyway, thank you~

**Comment by Wi1L-Y** [comment]
Hi,
sorry to bother, I have another question which may not be related to the project.

I just want to sniff BLE packets(not advertisement packets) using ubertooth or nRF52840? Do you have some method? I'm sorry to ask this question which is not so related to the project
